// Auto-generated by scripts/build-insights.mjs — do not edit by hand.
// Regenerated on every build from PDFs in /public/insights/.

export interface Insight {
  slug: string;
  date: string;
  title: string;
  summary: string;
  tags: string[];
  author: string;
  pdf: string;
  ogImage: string;
  sizeBytes: number;
}

export const insights: Insight[] = [];
